Repository monadicus/mentat, pull requests merged in 2022-04, with the labels that each got.

#68 Performance/closure api methods
  mentat-macros/src/lib.rs
  mentat/Cargo.toml
  mentat/src/api/call.rs
  mentat/src/api/construction.rs
  mentat/src/api/data.rs
  mentat/src/api/indexer.rs
  mentat/src/conf/configuration.rs
  mentat/src/identifiers/network_identifier.rs
  mentat/src/server/dummy_call.rs
  mentat/src/server/dummy_construction.rs
  mentat/src/server/dummy_data.rs
  mentat/src/server/dummy_indexer.rs
  mentat/src/server/mod.rs
  mentat/src/server/serve.rs
  rosetta-snarkos/conf.toml
Labels: enhancement

#70 Moved route generation to proc macro
  mentat-macros/src/lib.rs
  mentat-macros/src/route_builder.rs
  mentat/src/lib.rs
  mentat/src/server/mod.rs
  mentat/src/server/rpc_caller.rs
  mentat/src/server/serve.rs
  rosetta-bitcoin/conf.toml
  rosetta-bitcoin/src/main.rs
  rosetta-bitcoin/src/node.rs
Labels: implementation

#73 [Docs] Adds Licenses
  crate_licenses/LICENSE.color-backtrace
  crate_licenses/LICENSE.ed25519-dalek
  crate_licenses/LICENSE.indexmap
  crate_licenses/LICENSE.mina-hasher
  crate_licenses/LICENSE.mina-signer
  crate_licenses/LICENSE.open-telemetry-jaeger
  crate_licenses/LICENSE.open-telemetry-rust
  crate_licenses/LICENSE.p256
  crate_licenses/LICENSE.rand
  crate_licenses/LICENSE.reqwest
  crate_licenses/LICENSE.serde
  crate_licenses/LICENSE.serde-json
  crate_licenses/LICENSE.toml-rs
  crate_licenses/LICENSE.tracing-tree
Labels: documentation

#81 [Feature] Skip serde serialize on models based on rosetta-sdk-go
  mentat/src/errors/mod.rs
  mentat/src/misc/peer.rs
  mentat/src/misc/sync_status.rs
  mentat/src/misc/version.rs
  mentat/src/models/allow.rs
  mentat/src/models/balance_exemption.rs
  mentat/src/models/related_transaction.rs
  mentat/src/models/signing_payload.rs
  mentat/src/models/transaction.rs
  mentat/src/requests/account_balance.rs
  mentat/src/requests/account_coins.rs
  mentat/src/requests/construction_metadata.rs
  mentat/src/requests/construction_payloads.rs
  mentat/src/requests/construction_preprocess.rs
  mentat/src/requests/event_blocks.rs
  mentat/src/requests/metadata.rs
  mentat/src/requests/search_transactions.rs
  mentat/src/responses/account_balance.rs
  mentat/src/responses/account_coins.rs
  mentat/src/responses/block.rs
  mentat/src/responses/construction_derive.rs
  mentat/src/responses/construction_metadata.rs
  mentat/src/responses/construction_parse.rs
  mentat/src/responses/construction_preprocess.rs
  mentat/src/responses/mempool_transaction.rs
  mentat/src/responses/network_status.rs
  mentat/src/responses/search_transactions.rs
Labels: feature

#78 [Example] Client CLI Example
  .gitignore
  Cargo.lock
  Cargo.toml
  crate_licenses/LICENSE.anyhow
  crate_licenses/LICENSE.axum
  crate_licenses/LICENSE.clap
  crate_licenses/LICENSE.from-tuple
  crate_licenses/LICENSE.hyper
  crate_licenses/LICENSE.secp256k1
  crate_licenses/LICENSE.tower
  crate_licenses/LICENSE.tracing
  crate_licenses/LICENSE.tracing-error
  crate_licenses/LICENSE.tracing-opentelemetry
  crate_licenses/LICENSE.tracing-subscriber
  examples/mentat-cli/Cargo.toml
  examples/mentat-cli/src/account.rs
  examples/mentat-cli/src/block.rs
  examples/mentat-cli/src/main.rs
  examples/mentat-cli/src/mempool.rs
  examples/mentat-cli/src/network.rs
  mentat/Cargo.toml
  mentat/src/api/call.rs
  mentat/src/api/construction.rs
  mentat/src/api/data.rs
  mentat/src/api/indexer.rs
  mentat/src/api/mod.rs
  mentat/src/cache/cache_struct.rs
  mentat/src/client.rs
  mentat/src/errors/api_error.rs
  mentat/src/errors/mod.rs
  mentat/src/errors/server_error.rs
  mentat/src/identifiers/account_identifier.rs
  mentat/src/identifiers/block_identifier.rs
  mentat/src/identifiers/coin_identifier.rs
  mentat/src/identifiers/network_identifier.rs
  mentat/src/identifiers/operation_identifier.rs
  mentat/src/identifiers/partial_block_identifier.rs
  mentat/src/identifiers/sub_account_identifier.rs
  mentat/src/identifiers/sub_network_identifier.rs
  mentat/src/identifiers/transaction_identifier.rs
  mentat/src/lib.rs
  mentat/src/models/currency.rs
  mentat/src/requests/block.rs
  mentat/src/requests/block_transaction.rs
  mentat/src/requests/mempool_transaction.rs
  rosetta-bitcoin/src/data_api.rs
Labels: feature

#83 [Impl] Health Check
  Cargo.lock
  README.md
  mentat-macros/src/lib.rs
  mentat-macros/src/route_builder.rs
  mentat/Cargo.toml
  mentat/src/api/call.rs
  mentat/src/api/construction.rs
  mentat/src/api/data.rs
  mentat/src/api/indexer.rs
  mentat/src/api/mod.rs
  mentat/src/api/optional.rs
  mentat/src/conf/configuration.rs
  mentat/src/lib.rs
  mentat/src/responses/health_check.rs
  mentat/src/responses/mod.rs
  mentat/src/server/middleware_checks.rs
  mentat/src/server/mod.rs
  rosetta-bitcoin/src/main.rs
  rosetta-bitcoin/src/node.rs
  rosetta-bitcoin/src/optional_api.rs
  rosetta-bitcoin/src/responses/error.rs
  rosetta-snarkos/src/construction_api.rs
  rosetta-snarkos/src/data_api.rs
  rosetta-snarkos/src/macros.rs
  rosetta-snarkos/src/main.rs
  rosetta-snarkos/src/node.rs
  rosetta-snarkos/src/optional_api.rs
  rosetta-snarkos/src/responses/construction/sendtransaction.rs
  rosetta-snarkos/src/responses/data/getblock.rs
  rosetta-snarkos/src/responses/data/getblocktransactions.rs
  rosetta-snarkos/src/responses/data/getmemorypool.rs
  rosetta-snarkos/src/responses/data/gettransaction.rs
  rosetta-snarkos/src/responses/data/mod.rs
  rosetta-snarkos/src/responses/error.rs
  rosetta-snarkos/src/responses/response.rs
Labels: implementation

#90 [Impl] 404 catch, Allow user to specify middlewares and tracing conf
  mentat-macros/src/lib.rs
  mentat/src/conf/configuration.rs
  mentat/src/errors/server_error.rs
  mentat/src/identifiers/network_identifier.rs
  mentat/src/server/logging.rs
  mentat/src/server/middleware_checks.rs
  mentat/src/server/mod.rs
Labels: implementation
