Repository monadicus/mentat, pull requests merged in 2022-05, with the labels that each got.

#89 Add tests for signature schemes
  Cargo.lock
  mentat/Cargo.toml
  mentat/src/keys/aleo.rs
  mentat/src/keys/edwards25519.rs
  mentat/src/keys/pallas.rs
  mentat/src/keys/secp256k1.rs
  mentat/src/keys/secp256r1.rs
Labels: implementation

#93 [Impl] Generic Rpc call
  README.md
  mentat/src/conf/configuration.rs
  mentat/src/lib.rs
  mentat/src/server/mod.rs
  mentat/src/server/rpc_caller.rs
  rosetta-bitcoin/src/responses/response.rs
  rosetta-snarkos/src/construction_api.rs
  rosetta-snarkos/src/data_api.rs
  rosetta-snarkos/src/macros.rs
  rosetta-snarkos/src/main.rs
  rosetta-snarkos/src/request.rs
  rosetta-snarkos/src/responses/response.rs
Labels: implementation

#96 Feature/health check node connections
  mentat-macros/src/route_builder.rs
  mentat/src/api/optional.rs
  mentat/src/responses/health_check.rs
  rosetta-bitcoin/src/optional_api.rs
  rosetta-bitcoin/src/responses/mod.rs
  rosetta-bitcoin/src/responses/optional/mod.rs
  rosetta-snarkos/src/optional_api.rs
Labels: feature

#100 [Fix] custom config generation for empty structs
  Cargo.toml
  mentat/src/conf/configuration.rs
Labels: Fix
