Repository monadicus/mentat, pull requests merged in 2022-03, with the labels that each got.

#22 added `/call` endpoint
  src/api/call.rs
  src/api/mod.rs
  src/server/bitcoin_call.rs
  src/server/dummy_call.rs
  src/server/mod.rs
Labels: feature

#28 [Impl] Release Profiles
  .cargo/config.toml
  rosetta-bitcoin/Cargo.toml
  rosetta-snarkos/Cargo.toml
Labels: feature

#31 Endpoints
  Cargo.lock
  mentat/Cargo.toml
  mentat/src/api/call.rs
  mentat/src/api/construction.rs
  mentat/src/api/data.rs
  mentat/src/api/indexer.rs
  mentat/src/api/mod.rs
  mentat/src/errors/mod.rs
  mentat/src/lib.rs
  mentat/src/responses/block_transaction.rs
  mentat/src/server/logging.rs
  mentat/src/server/mod.rs
  rosetta-bitcoin/src/call_api.rs
  rosetta-bitcoin/src/construction_api.rs
  rosetta-bitcoin/src/data_api.rs
  rosetta-bitcoin/src/indexer_api.rs
  rosetta-snarkos/src/construction_api.rs
  rosetta-snarkos/src/data_api.rs
  rosetta-snarkos/src/macros.rs
  rosetta-snarkos/src/main.rs
  rosetta-snarkos/src/request.rs
  rosetta-snarkos/src/responses/common/mod.rs
  rosetta-snarkos/src/responses/common/snarkos_event.rs
  rosetta-snarkos/src/responses/common/snarkos_transaction.rs
  rosetta-snarkos/src/responses/common/snarkos_transactions.rs
  rosetta-snarkos/src/responses/common/snarkos_transition.rs
  rosetta-snarkos/src/responses/construction/mod.rs
  rosetta-snarkos/src/responses/construction/sendtransaction.rs
  rosetta-snarkos/src/responses/data/getblock.rs
  rosetta-snarkos/src/responses/data/getblocktransactions.rs
  rosetta-snarkos/src/responses/data/getmemorypool.rs
  rosetta-snarkos/src/responses/data/gettransaction.rs
  rosetta-snarkos/src/responses/data/mod.rs
  rosetta-snarkos/src/responses/error.rs
  rosetta-snarkos/src/responses/mod.rs
  rosetta-snarkos/src/responses/response.rs
Labels: feature

#34 Implement Aleo signature scheme
  Cargo.lock
  mentat/Cargo.toml
  mentat/src/keys/aleo.rs
  mentat/src/keys/errors.rs
  mentat/src/keys/mod.rs
  mentat/src/lib.rs
Labels: enhancement, feature

#38 Docs and License
  LICENSE
  README.md
Labels: documentation

#48 Feature Conf File
  Cargo.lock
  examples/dummy_server/src/main.rs
  mentat/Cargo.toml
  mentat/src/api/call.rs
  mentat/src/api/construction.rs
  mentat/src/api/data.rs
  mentat/src/api/indexer.rs
  mentat/src/api/mod.rs
  mentat/src/api/mode.rs
  mentat/src/conf/configuration.rs
  mentat/src/conf/mod.rs
  mentat/src/conf/mode.rs
  mentat/src/conf/network.rs
  mentat/src/identifiers/network_identifier.rs
  mentat/src/lib.rs
  mentat/src/server/middleware_checks.rs
  mentat/src/server/mod.rs
  mentat/src/server/node.rs
  mentat/src/server/rpc_caller.rs
  mentat/src/server/serve.rs
  rosetta-bitcoin/Cargo.toml
  rosetta-bitcoin/conf.toml
  rosetta-bitcoin/src/call_api.rs
  rosetta-bitcoin/src/construction_api.rs
  rosetta-bitcoin/src/data_api.rs
  rosetta-bitcoin/src/indexer_api.rs
  rosetta-bitcoin/src/main.rs
  rosetta-snarkos/Cargo.toml
  rosetta-snarkos/conf.toml
  rosetta-snarkos/src/construction_api.rs
  rosetta-snarkos/src/data_api.rs
  rosetta-snarkos/src/macros.rs
  rosetta-snarkos/src/main.rs
  rosetta-snarkos/src/node.rs
  temp.rs
Labels: enhancement

#49 Default features false all
  Cargo.lock
  mentat/Cargo.toml
Labels: enhancement

#56 [Impl] optional config
  Cargo.lock
  Cargo.toml
  examples/dummy_server/Cargo.toml
  examples/dummy_server/src/main.rs
  mentat/src/conf/configuration.rs
  mentat/src/identifiers/network_identifier.rs
  mentat/src/server/middleware_checks.rs
  mentat/src/server/mod.rs
  mentat/src/server/rpc_caller.rs
  mentat/src/server/serve.rs
  rosetta-bitcoin/src/main.rs
  rosetta-snarkos/src/main.rs
Labels: feature

#67 [Impl] Issue Templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
  .gitignore
  rosetta-snarkos/conf.toml
  temp.rs
Labels: implementation
